ADDING_OPERAND = '+'
SUBTRACT_OPERAND = '-'
MULTIPLY_OPERAND = '*'
DIVIDE_OPERAND = '/'
PLUS_OPERAND = '+'
SQUARE_OPERAND = '**'
EXPRESSION_TYPE = 'exp'

# URLS
BASE_CALCULATION_URL = '/api/v1/calculate'
SQUARE_CALCULATION_URL = '/api/v1/calculate_square'
